<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PINENOIL11198" name="TestCases.tidRigstrationTest" tests="6" failures="1" timestamp="29 Jan 2019 14:38:43 GMT" time="163.023" errors="0">
  <testcase name="approveStore" time="30.550" classname="TestCases.tidRigstrationTest"/>
  <testcase name="createStore" time="26.248" classname="TestCases.tidRigstrationTest"/>
  <testcase name="terminalCreationt" time="21.164" classname="TestCases.tidRigstrationTest"/>
  <testcase name="createMerchant" time="32.524" classname="TestCases.tidRigstrationTest"/>
  <testcase name="approveMerchant" time="33.486" classname="TestCases.tidRigstrationTest"/>
  <testcase name="tidRegistration" time="19.051" classname="TestCases.tidRigstrationTest">
    <failure type="java.lang.StringIndexOutOfBoundsException" message="String index out of range: 48">
      <![CDATA[java.lang.StringIndexOutOfBoundsException: String index out of range: 48
	at java.lang.String.substring(String.java:1951)
	at cimbui.Pages.registerTID.tidRegister(registerTID.java:122)
	at TestCases.tidRigstrationTest.tidRegistration(tidRigstrationTest.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1039)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:964)
	at org.testng.TestNG.run(TestNG.java:900)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase>
</testsuite>
